/**
 * Generating the modules a proof is checked in.
 *
 * The design rule here is the one the whole system rests on: **the prover never
 * supplies the theorem statement.** The checker derives it from the requirement
 * CID and the artifact CID, writes the signature line itself, and admits the
 * prover's text only in positions where it can be a justification and nothing
 * else.
 *
 * Without that rule, everything downstream is theatre. A prover free to write
 * the statement writes `def NotGerrymandered (_ : Plan) := True` and proves it
 * in one line, and every label the system issues is worthless — not because the
 * proof was wrong, but because nobody checked what was proved.
 *
 * The statement therefore lives in its own module, compiled before the prover's
 * text is elaborated at all. That gives two independent defences against
 * substitution: the prover cannot redefine `Obligation.stmt` because it is
 * already declared in an imported module, and the signature that mentions it was
 * written and elaborated where the prover's text does not reach.
 */

import { emitRawPlan } from './emit.js'
import type { StrongRef } from '../atp/network.js'

export type ObligationInputs = {
  artifact: StrongRef
  requirement: StrongRef
  theory: StrongRef
  /** Fully-qualified predicate from the requirement record, e.g. `Redistrict.FairDistrictingAct.section2`. */
  leanProp: string
  /** The artifact record as published. */
  artifactRecord: Record<string, unknown>
}

/**
 * Resource limits baked into every generated module.
 *
 * Generous, and set by the checker rather than the prover: a payload that could
 * raise its own limits could also spin the kernel until the checker gives up,
 * and a timeout is not a verdict.
 */
const LIMITS = ['set_option maxRecDepth 100000', 'set_option maxHeartbeats 1000000']

/** `Redistrict.FairDistrictingAct.section2` must be a plain dotted Lean name. */
const LEAN_NAME = /^[A-Za-z_][A-Za-z0-9_'!?]*(\.[A-Za-z_][A-Za-z0-9_'!?]*)*$/

export function checkLeanName(name: string, field: string): string {
  if (!LEAN_NAME.test(name)) {
    throw new Error(`${field} is not a plain Lean name: ${JSON.stringify(name)}`)
  }
  return name
}

function provenance(i: ObligationInputs): string {
  return [
    '-- Generated by the checker. Do not edit; regenerate from the records below.',
    '--',
    '--   artifact     ' + i.artifact.uri,
    '--                ' + i.artifact.cid,
    '--   requirement  ' + i.requirement.uri,
    '--                ' + i.requirement.cid,
    '--   theory       ' + i.theory.uri,
    '--                ' + i.theory.cid,
    '--',
    '-- Any edit to any of those three records changes its CID, which invalidates',
    '-- the proof that cites it rather than silently changing what was proved.',
  ].join('\n')
}

/**
 * The statement module. Contains no prover text of any kind.
 *
 * `Codec.decodePlanD` is total: an artifact that does not decode becomes
 * `Codec.rejected`, which fails the well-formedness clause every published
 * requirement opens with. So a malformed record yields a false obligation rather
 * than a vacuous one — the prover has to prove something untrue instead of
 * finding nothing to prove.
 */
export function statementModule(i: ObligationInputs): string {
  return `${provenance(i)}

import Redistrict
import Provable

${LIMITS.join('\n')}

namespace Obligation

/-- Transliteration of the artifact record, field for field. -/
def raw : Redistrict.Codec.Raw :=
${emitRawPlan(i.artifactRecord)}

/-- The plan those bytes denote, per the decoder named in the theory record.
Decoding lives in the theory, not here, so that two checkers cannot disagree
about what a record means. -/
def plan : Redistrict.Plan := Redistrict.Codec.decodePlanD raw

/-- The obligation. This is the proposition the prover must establish, and it is
derived from the requirement and the artifact rather than supplied.

Reducible, so that a tier-1 requirement can be discharged by \`decide\` without
the prover having to unfold a checker-internal name. Reducibility costs nothing
here: the protection against substitution is that this declaration is *imported*
by the proof module, so redefining it is a duplicate-declaration error, and the
signature that mentions it was elaborated before any prover text was read. -/
abbrev stmt : Prop := ${i.leanProp} plan

end Obligation
`
}

/**
 * A module that reports what evaluation alone can determine.
 *
 * Run regardless of whether the proof succeeds. When it fails, this is what
 * turns "the conjunction did not hold" into "the efficiency-gap clause did not
 * hold, and here is the gap"; when it succeeds, it is the summary a reader who
 * will never run Lean can check the verdict against.
 */
export function diagnoseModule(i: ObligationInputs): string {
  return `${provenance(i)}

import Obligation.Statement

${LIMITS.join('\n')}

def main : IO Unit := do
  IO.println ("CLAUSES " ++ Redistrict.clauseReport (${i.leanProp}.clauses Obligation.plan))
  IO.println ("SUMMARY " ++ Obligation.plan.summaryJson)
  IO.println ("DECODED " ++ (match Redistrict.Codec.decodePlan Obligation.raw with
    | .ok _ => "ok"
    | .error e => "error: " ++ e))

#eval main
`
}

/**
 * The proof module. The only file the prover's text appears in, and it appears
 * in exactly two places, both of which are justifications rather than claims.
 *
 * The signature line is written here, by the checker, referring to the
 * `Obligation.stmt` it imported. Auxiliary lemmas are confined to a namespace
 * opened only for this one declaration.
 */
export function proofModule(
  i: ObligationInputs,
  payload: string,
  lemmas: string | undefined,
  allowedAxioms: string[],
): string {
  const allowing = ` allowing [${allowedAxioms.join(', ')}]`
  return `${provenance(i)}
--
-- Everything outside the two PROVER PAYLOAD regions is checker-authored. In
-- particular the theorem's signature is, so the prover chooses how to prove the
-- obligation but not what the obligation says.

import Obligation.Statement

${LIMITS.join('\n')}

namespace Obligation.Prover
-- ↓↓↓ PROVER PAYLOAD: auxiliary lemmas ↓↓↓
${lemmas ?? '-- (none supplied)'}
-- ↑↑↑ END PROVER PAYLOAD ↑↑↑
end Obligation.Prover

open Obligation.Prover in
theorem Obligation.proof : Obligation.stmt :=
-- ↓↓↓ PROVER PAYLOAD: proof term ↓↓↓
${payload}
-- ↑↑↑ END PROVER PAYLOAD ↑↑↑

-- The load-bearing check. A build that succeeds having quietly used \`sorry\`,
-- native evaluation, or a prover-declared axiom fails here instead, with a
-- nonzero exit code.
#assert_axioms Obligation.proof${allowing}
`
}
